basePath: /api/v1
info:
  contact: {}
paths:
  /doctor:
    get:
      consumes:
      - application/json
      description: get doctors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Doctors
      tags:
      - doctors
    post:
      consumes:
      - application/json
      description: post doctors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Post Doctors
      tags:
      - doctors
swagger: "2.0"
